lint: {}
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Benjamin Wehnert & Maximilian R. Stammnitz
  description: "Processing and analysis of deep mutational scanning (DMS) data from shotgun and amplicon sequencing: read alignment, variant counting, sequencing-error correction, library QC and fitness estimation"
  force: false
  is_nfcore: true
  name: deepmutscan
  org: nf-core
  outdir: .
  version: 1.0.0
